test = {
    "trainer_maeeg_pretrain_config": {
        "run_name": "maeeg_512_enc768_dec256",
        "lr": 0.0001,
        "weight_decay": 0.07,
        "num_epochs": 200,
        "warmup_epochs": 10,
        "batch_size": 60,
        "num_workers": 2,
        "clip_grad": 0.8,
        "time_len": 640,
        "hop_length": 128,
        "data_path": "/mnt/nvme/node02/pranav/AE24/data/split_data",
        "output_path": "/mnt/nvme/node02/pranav/AE24/chitVachana/cape",
        "reload_path": "",
        "resume_wandb": "",
        "normalize_data": 2,
        "seed": 2024,
    },
    "trainer_maeeg_align_config": {
        "run_name": "maeeg_align_freeze_gpt",
        "lr": 0.001,
        "weight_decay": 0.07,
        "num_epochs": 100,
        "warmup_epochs": 0,
        "freeze": True,
        "batch_size": 256,
        "num_workers": 8,
        "clip_grad": 0.8,
        "data_path": "/mnt/nvme/node02/pranav/AE24/data/split_data",
        "output_path": "/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne",
        "reload_path": "/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne/checkpoint/maeeg_align_freeze_gpt_1data_16-04-2024-11-43.ckpt",
        "resume_wandb": "",
        "normalize_data": 2,
        "subset": 0.5,
        "seed": 2024,
        "weight": 0.8,
    },
    "trainer_ldm_config": {
        "run_name": "ldm_finetune",
        "lr": 0.001,
        "weight_decay": 0.07,
        "num_epochs": 100,
        "warmup_epochs": 10,
        "freeze": True,
        "batch_size": 120,
        "num_workers": 8,
        "clip_grad": 0.8,
        "data_path": "/mnt/nvme/node02/pranav/AE24/data/split_data",
        "output_path": "/mnt/nvme/node02/pranav/AE24/chitVachana/ldm_models",
        "reload_path": "",
        "resume_wandb": "",
        "normalize_data": 2,
        "subset": 1,
        "seed": 2024,
        "weight": 0.8,
    },
    "ldm_config": {
        "params": {"in_channels": 1, "t_steps": 1, "img_depth": 1, "num_tsteps": 1}
    },
    "dataset_config": {
        "preprocessing": {
            "audio": {
                "sampling_rate": 16000,
                "max_wav_value": 32768.0,
                "duration": 10,
                "hop_length": 4,
            },
            "stft": {"filter_length": 1024, "hop_length": 160, "win_length": 1024},
            "mel": {"n_mel_channels": 64, "mel_fmin": 0, "mel_fmax": 8000},
        }
    },
    "maeeg_config": {
        "params": {
            "img_size": (64, 640),
            "in_chans": 1,
            "patch_size": (8, 10),
            "enc_embed_dim": 768,
            "enc_depth": 10,
            "enc_num_heads": 12,
            "dec_embed_dim": 256,
            "dec_depth": 6,
            "dec_num_heads": 8,
            "mlp_ratio": 4,
            "norm_layer": "",
            "pos_trainable": False,
            "pos_dim": 1,
            "mask_ratio": 0,
        }
    },
    "seq_config": {
        "params": {
            "always_output_audiomae_gt": False,
            "learnable": True,
            "use_gt_mae_output": True,
            "use_gt_mae_prob": 1,
            "base_learning_rate": 0.0002,
            "sequence_gen_length": 512,
            "use_warmup": True,
            "sequence_input_key": ["crossattn_vits_phoneme"],
            "sequence_input_embed_dim": [192],
            "batchsize": 16,
            "cond_stage_config": {
                "crossattn_vits_phoneme": {
                    "cond_stage_key": "phoneme_idx",
                    "conditioning_key": "crossattn",
                    "target": "audioldm2.latent_diffusion.modules.encoders.modules.PhonemeEncoder",
                    "params": {
                        "vocabs_size": 183,
                        "pad_token_id": 0,
                        "pad_length": 310,
                    },
                },
                "crossattn_audiomae_pooled": {
                    "cond_stage_key": "ta_kaldi_fbank",
                    "conditioning_key": "crossattn",
                    "target": "audioldm2.latent_diffusion.modules.encoders.modules.AudioMAEConditionCTPoolRand",
                    "params": {
                        "regularization": False,
                        "no_audiomae_mask": True,
                        "time_pooling_factors": [1],
                        "freq_pooling_factors": [1],
                        "eval_time_pooling": 1,
                        "eval_freq_pooling": 1,
                        "mask_ratio": 0,
                    },
                },
            },
        }
    },
    "run_name": "maeeg_align_freeze_gpt",
    "lr": 0.001,
    "weight_decay": 0.07,
    "num_epochs": 100,
    "warmup_epochs": 0,
    "freeze": True,
    "batch_size": 256,
    "num_workers": 8,
    "clip_grad": 0.8,
    "data_path": "/mnt/nvme/node02/pranav/AE24/data/split_data",
    "output_path": "/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne",
    "reload_path": "/mnt/nvme/node02/pranav/AE24/chitVachana/cape/aligne/checkpoint/maeeg_align_freeze_gpt_1data_16-04-2024-11-43.ckpt",
    "resume_wandb": "",
    "normalize_data": 2,
    "subset": 0.5,
    "seed": 2024,
    "weight": 0.8,
}
